### ISSUE TITLE
breaks with python 3.6

### ISSUE THREAD

**Issue by cyphx** [arunanshub/sphinx-nested-apidoc#1]
This breaks on my current python installation. I am on python 3.6 right now, but I can't migrate to higher version because of some breaking dependenciesThe version information should be mentioned at the very least. If possible, can you port it to work with something like 3.6 ?

**Comment by arunanshub** [comment]
@cyphx, Can you provide the exact traceback?

**Comment by arunanshub** [comment]
Fixed this in `v0.3.2`.
