### ISSUE TITLE
Is it possible to include `sphinx-nested-apidoc` output into existing toctree?

### ISSUE THREAD

**Issue by pseusys** [arunanshub/sphinx-nested-apidoc#14]
I'm trying to add auto generated documentation into existing toctree root. Documentation is generated with this command:
```
sphinx-nested-apidoc -f -o docs/source/build src
```
And then trying to include it into existing toctree like this:
```
.. toctree::
   :caption: Auto Docs

   apiref/modules
```
but that doesn't seem to work: `sphinx-nested-apidoc` generates `index.rst` in each directory and then includes these directories by name.  
I haven't found any evidence that `index.rst` can become a default include of directory when directory is included into toctree - and I receive a lot of warning messages like `toctree contains reference to nonexisting document '[filename]'`.

Is there any way the output of `sphinx-nested-apidoc` can be included into toctree without modifications? Maybe you can share an example?

**Comment by arunanshub** [comment]
> I'm trying to add auto generated documentation into existing toctree root. Documentation is generated with this command:
> 
> ```
> sphinx-nested-apidoc -f -o docs/source/build src
> ```

It looks like you are trying to put `rst` files in the build directory. However, build is supposed to contain the static webpages generated by sphinx itself.

> I haven't found any evidence that `index.rst` can become a default include of directory when directory is included into toctree - and I receive a lot of warning messages like `toctree contains reference to nonexisting document '[filename]'`.

According to the [documentation](https://github.com/arunanshub/sphinx-nested-apidoc#some-additional-details), `sphinx-nested-apidoc` will not modify the contents of the files. It is up to the user.

> Is there any way the output of `sphinx-nested-apidoc` can be included into toctree without modifications? Maybe you can share an example?

I believe what you are looking for is the exclusion of `--force` flag. `--force` instructs `sphinx-nested-apidoc` to replace existing files with the newly generated ones. The removal of the flag will leave the existing documentation files intact.

Can you provide more information about the problem you are facing?

**Comment by pseusys** [comment]
Could you please maybe provide a sample `conf.py` and (if needed) `index.rst` files for building documentation, generated with `sphinx-nested-apidoc` into, say, HTML?

**Comment by pseusys** [comment]
Yeah, I see, thank you!

**Comment by arunanshub** [comment]
Have your issue been resolved?
