### ISSUE TITLE
Configure nested-apidoc in conf.py

### ISSUE THREAD

**Issue by GrossTor** [arunanshub/sphinx-nested-apidoc#2]
Is it possible to have sphinx-nested-apidoc be enabled and configured from the conf.py file, as with apidoc in [sphinxcontrib-apidoc](https://github.com/sphinx-contrib/apidoc)?

**Comment by arunanshub** [comment]
Currently, no. But I am open to suggestions/pull requests on this matter. Would you like to look into this?
